// <auto-generated />
namespace SportsStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class added_category_to_prod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_category_to_prod));
        
        string IMigrationMetadata.Id
        {
            get { return "201404201430374_added_category_to_prod"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
